/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const EmployeesLazyImport = createFileRoute('/employees')()
const CafesLazyImport = createFileRoute('/cafes')()
const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const EmployeesLazyRoute = EmployeesLazyImport.update({
  path: '/employees',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/employees.lazy').then((d) => d.Route))

const CafesLazyRoute = CafesLazyImport.update({
  path: '/cafes',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/cafes.lazy').then((d) => d.Route))

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/cafes': {
      id: '/cafes'
      path: '/cafes'
      fullPath: '/cafes'
      preLoaderRoute: typeof CafesLazyImport
      parentRoute: typeof rootRoute
    }
    '/employees': {
      id: '/employees'
      path: '/employees'
      fullPath: '/employees'
      preLoaderRoute: typeof EmployeesLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexLazyRoute,
  CafesLazyRoute,
  EmployeesLazyRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/cafes",
        "/employees"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/cafes": {
      "filePath": "cafes.lazy.tsx"
    },
    "/employees": {
      "filePath": "employees.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
